### ISSUE TITLE
Help for get information loss metric

### ISSUE THREAD

**Issue by milad1370s** [arx-deidentifier/arx#109]
thanks for arx lib its very helpful for me, i use 
adult data set and anonymiz it, at the end i should get the information loss 
and DM metric for compare with another solution, can you show how i can use 
and get result for information loss after anonymize data? and how to understand and Analysis the result of metric, can you give me a 
example? 
thanks a lot

**Comment by prasser** [comment]
Dear Milad,

thanks for your interest in ARX. Please contact us directly for questions regarding the use of ARX. This is a forum for reporting issues with the software. You can reach us at: arx.deidentifier@gmail.com.

Best regards
Fabian
