### ISSUE TITLE
Feature Request: Editing multiple attributes at once

### ISSUE THREAD

**Issue by codingbutstillalive** [arx-deidentifier/arx#124]
Hello!

Following up on our email correspondence, I would like to suggest to allow for the selection and editing of multiple attributes at once. For example, if one has more than 15-20 attributes, editing each attribute manually and separately becomes cumbersome.

It would be nice to be able to mark several attributes as quasi identifiers at once - or to select all except a few as quasi identifiers. Also, editing data types in that way (or assignments of equal generalization hierarchies) could be useful.

**Comment by prasser** [comment]
Thanks for this suggestion. In ARX 3.7.0. it will be possible to simultaneously assign a specific attribute type to all attributes in a dataset. While this doesn't cover all use cases mentioned here, it is probably a good intermediate solution. Please also note that data types can be auto-detected during import, so I think that this is less of an issue. I'm closing this now. Fabian
