### ISSUE TITLE
sorting data in a column

### ISSUE THREAD

**Issue by alisedaghatbaf** [arx-deidentifier/arx#145]
Hi, 

Thank you for developing such a powerful and flexible tool for data anonymization. In order to enable sorting data per column, I've modified the implementation of the DataTableGridLayer class by (1) defining a SortHeaderLayer on top of the columnHeaderLayer:
    SortHeaderLayer<String[]> sortHeaderLayer = new SortHeaderLayer<>(columnHeaderLayer, this.sortModel);
 (2) passing this layer to the cornerLayer:
    ILayer cornerLayer = new CornerLayer(cornerDataLayer, rowHeaderLayer, sortHeaderLayer);
and (3) setting that layer as the column header layer of the gridLayer:
    setColumnHeaderLayer(sortHeaderLayer);
The sort functionality works fine now, but in cases that the sum of columns width is less than the width of the wrapper composite, table body is empty, i.e., only the row/column headers are displayed. A snapshot is attached. Any help would be appreciated.
<img width="489" alt="capture" src="https://user-images.githubusercontent.com/31185263/33315707-b94e8190-d446-11e7-8b2d-2474f8c5f078.PNG">

**Comment by prasser** [comment]
Thank you for your interest in ARX!

ARX already supports sorting the data by selected columns. First, you need to select a column then you need to press either the up- or down-arrow displayed in the right top corner of the table.

Why are you implementing a new method?

Thanks
Fabian

**Comment by alisedaghatbaf** [comment]
Thank you, maybe I'm using an old version.

**Comment by prasser** [comment]
Ok, I will close this issue now.
