### ISSUE TITLE
pageup/down keys

### ISSUE THREAD

**Issue by alisedaghatbaf** [arx-deidentifier/arx#152]
Hi, 
I've seen in the code that DefaultSelectionBindings has been added to UI configurations. However, pressing pageup/down keys has no effects i.e., the scrollbar does not move.

**Comment by prasser** [comment]
Thanks for reporting this issue. Can you try to debug it and propose a fix? Thanks, Fabian

**Comment by alisedaghatbaf** [comment]
this line of code should be added to the constructor of DataTableSelectionLayer:

`registerCommandHandler(new MoveRowSelectionCommandHandler(this));`
