### ISSUE TITLE
Attribute 'gender': hierarchy misses some values or contains duplicates

### ISSUE THREAD

**Issue by giatrakister** [arx-deidentifier/arx#181]
Hi, i am developing a java class to anonymize some custom data. I have use the example code from here:
https://github.com/arx-deidentifier/arx/blob/master/src/example/org/deidentifier/arx/examples/Example6.java

as a starting point. With the test data it works but when i try to add my own data i get the error:
Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'gender': hierarchy misses some values or contains duplicates
	at org.deidentifier.arx.framework.data.GeneralizationHierarchy.<init>(Unknown Source)
	at org.deidentifier.arx.framework.data.DataManager.<init>(Unknown Source)
	at org.deidentifier.arx.ARXAnonymizer.getDataManager(Unknown Source)
	at org.deidentifier.arx.ARXAnonymizer.anonymize(Unknown Source)

The part of my code where i create tha data is:

 DefaultData data = Data.create();
        data.add("age", "gender", "zipcode");
        
            /* loop through json results */
            for (int i = 0; i < results.size(); i++) { 
                String age = results.get(i).getAsJsonObject().get("demographics").getAsJsonObject().get("age").toString();
                String gender = results.get(i).getAsJsonObject().get("demographics").getAsJsonObject().get("gender").toString().trim();
                
                
                data.add(age,gender,"81667"+i);
            }

I am using the arx-3.6.0-win-64.jar

Thank you in advance.

**Comment by giatrakister** [comment]
the data that i finally insert are: 
118  "female"  816670
118  "male"  816671
118  "male"  816672
118  "female"  816673
118  "female"  816674
118  "female"  816675
118  "female"  816676
118  "female"  816677
118  "female"  816678
118  "female"  816679
118  "female"  8166710
118  "female"  8166711
118  "female"  8166712
118  "female"  8166713
118  "female"  8166714
118  "female"  8166715
118  "female"  8166716
118  "female"  8166717
118  "female"  8166718
118  "female"  8166719
118  "female"  8166720
118  "female"  8166721
118  "female"  8166722
118  "female"  8166723
118  "female"  8166724
118  "female"  8166725
118  "female"  8166726
118  "female"  8166727

**Comment by prasser** [comment]
Thanks for your interest in ARX!

As indicated by the error message, the values used for gender do not match the values contained in the hierarchy. The reason is probably the double quotes but you will likely have the same issue with the values provided for zip code. The solution is to either provide a comprehensive hierarchy covering all possible values or to construct hierarchies dynamically. For the latter, you can either implement your own methods or use ARX's HierarchyBuilders. We have examples for this as well.

Best
Fabian

**Comment by giatrakister** [comment]
Thank you for your reply.

The running example that i started from has also double quotes in the data:

DefaultData data = Data.create();

        data.add("age", "gender", "zipcode");       
        data.add("34", "male", "81667");
        data.add("45", "female", "81675");
        data.add("66", "male", "81925");


and it works. In my custom data i have double quotes in gender which is where  got the error.Double quotes are also in the hierarchy code. What should change then?
And about the examples you mentioned, can i find them in the ARX webpages?

Thank you again!

**Comment by prasser** [comment]
No, the hierarchy does not contain double quotes. These are string literals, i.e. a series of characters that are enclosed in double quotes. The double quotes are not part of the actual string values. The examples are in the examples-package in the repository.

Best, Fabian

**Comment by giatrakister** [comment]
Yes, i removed the double quotes from my data and it works. Thank you very much.

I have one more question , in my example i have very few data and i know the content, but in real case scenario i will import my data as before but will not know the exact values to create the corresponding hierarchies. Is there a way to create them in a more general way? I have looked in most of the examples as mentioned but could not find something. Thanx again!

**Comment by prasser** [comment]
As noted before, you can either implement your own method or use ARX's HierarchyBuilders. Please take a look at:

Example18.java
Example24.java
Example25.java
Example26.java
Example28.java

I will close this issue now. If you have further questions, please contact us via email.
