### ISSUE TITLE
Do you guys support hadoop?

### ISSUE THREAD

**Issue by chmduquesne** [arx-deidentifier/arx#190]
Hi,

I am considering using arx. How big of an amount of data does it support? Can it be used to anonymize data on hadoop?

**Comment by prasser** [comment]
Hi,

thanks for your interest in ARX!

The current limitations are as follows: the dataset loaded into ARX must not have more than 2^31-1 cells (i.e. rows * columns). The solution space must not be larger than 2^63-1 transformations, which is roughly equivalent to ~40-50 key variables associated with non-trivial transformation rules. ARX relies on in-memory data processing, so the amount of RAM available is also a limiting factor.

We don't support Hadoop. However, depending on the privacy model that you want to use it would be relatively simple to use ARX as a primitive to build a distributed data anonymization framework: (1) distribute the data to different nodes, (2) anonymize the subsets independently, (3) merge the results.

Best regards
Fabian

**Comment by huda888** [comment]
Hi,,
Can I edit in ARX and use it to publish data in the Cloud?
I mean is it open source??

**Comment by wchennc** [comment]
@prasser 
In your suggestion, I wonder if generalization or micro-aggregation is used, how does each subset get to know the overall distribution of the entire dataset? Generalizing a subset without knowing the data in other subsets will lead to overly anonymized data , is it a right assumption? Any suggestion on this please?

**Comment by prasser** [comment]
@wchennc As mentioned above, this heavily depends on the privacy model, transformation model and utility model used. With most non-trivial transformation methods, you will generally only be able to compute a solution that is "good enough" (even in a non-distributed setting) and likely not optimal. In my experience, anonymizing data as a set of chunks typically works very well, but this depends on the aspects already mentioned as well as the concrete data set. In addition:
(1) You can tailor a protocol for your specific transformation model, e.g. by exchanging the transformation schemes computed for the different subsets and merging/combining them with each other in an intelligent manner.
(2) You can distribute data among nodes in an intelligent manner, e.g. by sorting records based on some measure of distance before creating the subsets.

**Comment by ebebpl** [comment]
Hello, any plans to increase the rows*columns sizes? 2GB seems really small in current times.

**Comment by prasser** [comment]
The limit is rows * columns < 2^31, which is not the same as 2 GB, as each cell  may hold much more than just one byte of data. However, if you want us to increase this limit, please create a separate pull request. Until this issue is resolved, we suggest to process data in different chunks as described above. Best, Fabian
