### ISSUE TITLE
Execution time of ARX

### ISSUE THREAD

**Issue by wei-yuan** [arx-deidentifier/arx#201]
### Problem statement
Hi 
I try to re-conduct the experiment in the literature of [ARX - A Comprehensive Tool for Anonymizing Biomedical Data](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4419984/pdf/1984395.pdf)
I follow the step of [Data De-Identification with the ARX Data Anonymization Tool](https://www.youtube.com/watch?v=N8I-sxmMfqQ) video
But I'm wondering how to **measure** the time properly just like figure 9 of the literature did?

### System info
OS: Ubuntu 16.04
ARX version: 3.7.0

**Comment by prasser** [comment]
Thanks for your interest in ARX! Please take a look at the tool tip in the top-right corner. You should, however, not measure execution times with the GUI. Best, Fabian

**Comment by wei-yuan** [comment]
@prasser 
Hi, thanks for the response!
You mention that 
1)  ... tool tip in the top-right corner  -> Do you mean ARX help center? 
2)  ... not measure execution times with the GUI -> But how do I measure the execution time? 

Sir, please shed some light, especially point 2. I would appreciate

**Comment by prasser** [comment]
1. From the documentation "ARX's application toolbar displays some information: (1) the currently selected transformation, (2) the currently applied transformation as well as some statistics collected during the anonymization process. These statistics include the number of privacy-preserving transformations and the total number of transformations in the solution space as well as some statistics about the search process." -> The tool tip is available in the area displaying the currently selected transformation.
2. I recommend to use the ARX Java library for experimental evaluations. See, e.g., here: https://github.com/arx-deidentifier/anonbench

Best
Fabian
