### ISSUE TITLE
Urgent help required ,Steps for installation 

### ISSUE THREAD

**Issue by mohsinsway** [arx-deidentifier/arx#205]
**Hello dear** , i am new in programming for my research purposes i have to install ARX code and show to my supervisor . I have tried my times but fail to install ARX , kindly give me detail of steps to ARX code so that my research can progress.
Wait for positive response

**Comment by prasser** [comment]
It is pretty straight-forward to import the project into Eclipse. Clone the repository. Create a new project pointing to the cloned directory using Eclipse's new project wizard. The wizard will automatically add all required dependencies (the jars) to the class path. Just make sure to remove the swt*.jars that are not for your platform. If you have further questions, please contact us via email: arx.deidentifier@gmail.com.

**Comment by mohsinsway** [comment]
If any installation video available it will be great favor for me.I have tried different versions of Eclipse but fail to install. Kindly help me to sort out this issues
