### ISSUE TITLE
Randomize order of tuples in output datasets

### ISSUE THREAD

**Issue by RaffaelBild** [arx-deidentifier/arx#218]
When presenting records in the output dataset in the same order they had in the input dataset, it may be possible to infer sensitive information by matching records using their row numbers. To avoid possible privacy issues resulting from this, in particular when using differential privacy, it might be worthwhile to randomly shuffle the order of records when output datasets are being exported.

**Comment by prasser** [comment]
Implemented in commit 18c3089. Closing.
