### ISSUE TITLE
Manual(support) for the first use of this tool

### ISSUE THREAD

**Issue by jophoenderdosWork** [arx-deidentifier/arx#225]
Hi there,

We are searching for a program that is capable to anonymize our medical data for internal testing and for the use of statistical analyses by an external company.  

We find on your website some publications which use the program for doing this kind of stuff. 

So we downloaded the tool and read the manual on your website and watched the instruction movie on your youtube account. But after this, we getting strange values in our output data.
What I was missed the most in the youtube movie is the “why”? So it is kind off hard for using for our data. 

So is there maybe another manual which we can follow? Or can we get some (paid) support for using this tool?

Hope to hear from you,

Jop Hoenderdos

**Comment by prasser** [comment]
Dear Jop,

thanks for your interest in ARX!

Unfortunately, we cannot provide you with a guideline or commercial  support. If you want to apply ARX in practice, you definitely need to know what you are doing, so I recommend to study existing guidelines. The following books may be a good *starting point* (there is a lot of literature on the topic):

- Luk Arbuckle, Khaled El Emam: Anonymizing Health Data - Case Studies and Methods to Get You Started
- Khaled El Emam: Guide to the De-Identification of Personal Health Information

Please send future questions about ARX to arx.deidentifier@gmail.com

Best
Fabian
