### ISSUE TITLE
Importing Mutiple Tables

### ISSUE THREAD

**Issue by senthilkumark7** [arx-deidentifier/arx#230]
Will it possible to import mutilple tables (from MS SQL Server ) in to project and do the anonymization ?

**Comment by prasser** [comment]
Thanks for your interest in ARX! This is currently not supported. If you want to import data from multiple tables, you need to perform preprocessing. If you can describe your requirements in detail, you could also open an issue with a feature request. We might then add this functionality in the future.

**Comment by senthilkumark7** [comment]
Thank you for the quick response.
1 .Required to do data anonymization for around 240 columns from around 80 tables
    Is it  possible to achieve this using a single project ?
2. if possible making  tables and columns as inputs ( like from text file)

**Comment by prasser** [comment]
Hi, as mentioned in my first response: you need to preprocess your data in order to be able to import it into a single project. Best, Fabian
