### ISSUE TITLE
String type attribute masking

### ISSUE THREAD

**Issue by Najjaf** [arx-deidentifier/arx#233]
Hi,

We have to apply data anonymization to our data for which we have selected ARX. Now the problem is, We want that for the string type attributes like name and address, masking should be enabled like if the name value is "Alexander" then it should be transformed to "AlXX***" or similar type of masking so that data wont be compromised and for our QA department testing would be easy. And most importantly this anonymization should not be de-anonymized. It must be one way and cannot be transformed back to "Alexander".

Any help in this regard is appreciated.

**Comment by prasser** [comment]
Hi,

thanks for your interest in ARX! Why don't you simply define them as identifying (and thereby replace them with "*")? If it should not be possible to go back to the original values, "*" seems to be as good as "AIXX***".

Best
Fabian

**Comment by Najjaf** [comment]
Thanks for your response. I did the same. Declared attribute as identifying then created hierarchy which lead me with 0 to 12 level hierarchy. Also selected privacy model for it named "(2, 1e-6)-Differential privacy" but after anonymization, it is showing "*" replacing all the values. I want only some of the characters masked with esterik "*" so that data can be somehow identified for QA department.

**Comment by prasser** [comment]
I'm not sure if I understand your requirements. It seems like, as if you want to implement data masking or pseudonymization. If so, this is currently not supported by ARX. Please see https://github.com/arx-deidentifier/arx/issues/203

What you can try, however, is to set the attribute type for the column to "quasi-identifying", select a generalization level that you want to apply (i.e. specify a fixed minimum and maximum level) and then perform anonymization with a neutral privacy model (I recommend (0, 1)-presence).

For additional help on how to use ARX, you can also take a look at our tutorial: https://www.youtube.com/watch?v=N8I-sxmMfqQ

I will close this issue now. Please direct further questions regarding the use of ARX towards arx.deidentifier@gmail.com
