### ISSUE TITLE
apply l-diversity on sensitive fields

### ISSUE THREAD

**Issue by giupardeb** [arx-deidentifier/arx#236]
Hi everybody! I have a dataset with different field and about 1000 rows.
I want use the l-diversity privacy model implemented into ARX on race field. 
When I click on Anonymize button, the race field of output dataset is equal to originally dataset.
What am I doing wrong?

**Comment by prasser** [comment]
Thanks for your interest in ARX!

You are doing nothing wrong. Sensitive attribute values are not changed during anonymization!

Please direct further questions regarding the use of ARX towards arx.deidentifier@gmail.com

Best
Fabian
