### ISSUE TITLE
Help for getting subset of data 

### ISSUE THREAD

**Issue by mohsinsway** [arx-deidentifier/arx#239]
Sir i am trying to read first few lines of  data from adult.CSV file 
Data data = Data.create("data/adult.csv", StandardCharsets.UTF_8, ';');
but this function did not work when load data form csv file
   **DataSubset subset = DataSubset.create(data, new HashSet<Integer>(Arrays.asList(1, 2,3)));**

**Comment by prasser** [comment]
Hi, please provide more details in the form of a minimal working example. Also, this sounds like a support question (not actually a bug). If so, please contact arx.deidentifier@gmail.com. Thanks
