### ISSUE TITLE
Error:(36, 30) java: can't find org.eclipse.swt.events

### ISSUE THREAD

**Issue by realRuiGuo** [arx-deidentifier/arx#245]

**Comment by realRuiGuo** [comment]
Error:(26, 32) java: 程序包org.eclipse.swt.graphics不存在

**Comment by realRuiGuo** [comment]
may i need run ant build？

**Comment by prasser** [comment]
Please take a look at: https://github.com/arx-deidentifier/arx/issues/204
Ant should not be needed. Best, Fabian
