### ISSUE TITLE
Fail to start on Ubuntu 16.04

### ISSUE THREAD

**Issue by jindaliitr** [arx-deidentifier/arx#246]
After installing eclipse and fresh installation of Arx and checking out psn branch I was unable to run the code. Though I have fixed the error by adding the dependency in pom.xml, so if you can see to it to either grant me access of pushing to this branch or apply this code change.

```
 <dependency>
	<groupId>org.eclipse.swt.org.eclipse.swt.gtk.linux.x86_64.4.3.swt</groupId>
    	<artifactId>org.eclipse.swt.gtk.linux.x86_64</artifactId>
	<version>4.3</version>
</dependency>
```

**Comment by prasser** [comment]
Thanks for your interest in ARX! Support for maven builds ins experimental. Especially in eclipse you should be able to also get the project up and running without using Ant or Maven. If you want to contribute to the project, please follow the Standard Fork & Pull Request Workflow (https://gist.github.com/Chaser324/ce0505fbed06b947d962). Best, Fabian
