### ISSUE TITLE
Automatically generate rules for anonymization

### ISSUE THREAD

**Issue by ronnypeterson** [arx-deidentifier/arx#249]
Is there any way to automatically generate anonymization policies for an attribute?

**Comment by prasser** [comment]
Semi-automatically, yes. Take a look [here](https://arx.deidentifier.org/anonymization-tool/configuration/#a23) for a description regarding the GUI and take a look at [here](https://github.com/arx-deidentifier/arx/tree/master/src/example/org/deidentifier/arx/examples) for examples on how to use the API. Best, Fabian

**Comment by ronnypeterson** [comment]
Thank you! I will try.
