### ISSUE TITLE
Question: estimateNonEmptyEquivalenceClasses parameters

### ISSUE THREAD

**Issue by fatima-a** [arx-deidentifier/arx#251]
In the ModelSNB.java file, the estimateNonEmptyEquivalenceClasses method uses the parameters n and n1. Are these the population and sample sizes respectively? And I'm assuming that 'histogram' is an ordered frequency distribution table for equivalence class sizes?

Thanks!

**Comment by prasser** [comment]
Dear Fatima,

thanks for taking such a deep look at ARX and sorry for the lack of documentation of these function parameters!

You can find out what the variables stand for by taking a look at how the method is called and how the histogram is built:

(1) n = number of equivalence classes
(2) n1 = number of classes of size 1
(3) histogram = represents the distribution of equivalence class sizes. It is an array of two-dimensional arrays where each entry i stores a size and a frequency (i[0]=class-size, i[1]=number of classes of this size). No entries are stored for class-sizes that don't exist in the distribution. Entries are sorted by class-size in ascending order.

Best
Fabian

**Comment by fatima-a** [comment]
That's perfect! Thank you so much for the prompt reply- its much appreciated.
