### ISSUE TITLE
[Support] create a empty DataColumn object

### ISSUE THREAD

**Issue by giupardeb** [arx-deidentifier/arx#252]
Hi all guys, is it possible create a empty DataColumn object ?

Thank you!

**Comment by prasser** [comment]
Hi Guiseppe,

I don't think so. Why would you want to do that? Please provide an example.

Best
Fabian

**Comment by giupardeb** [comment]
I'm working on algorithm that uses an empty ArrayList java. I would like to use a DataColumn instead ArrayList

**Comment by prasser** [comment]
Why? Please provide an example. Thanks, Fabian

**Comment by giupardeb** [comment]
I solved! I thought to need a empty DataColumn object , but I can use ArrayList like a support variable and then copy the result on DataColumn.

 Sorry if I wasted your time

Thank you so much

Best, Giuseppe
