### ISSUE TITLE
ARX win10 64bit 

### ISSUE THREAD

**Issue by jyf1997** [arx-deidentifier/arx#254]
java.lang.NoClassDefFoundError:org/apache/commons/logging/LogFactory

**Comment by prasser** [comment]
Thanks for reporting this. Please provide more details. Which version of ARX are you running? Are you running ARX from code or via an installation? What is the complete stack trace? Thanks, Fabian

**Comment by jyf1997** [comment]
@prasser
 I've got the source code from github, and I don't know which version it is.

There are several packages on my eclipse that can't be imported, and I don't know where it is!

The import rst.pdfbox.layout.elements.Document cannot be resolved

The import rst.pdfbox.layout.elements.Document cannot be resolved.

The import rst.pdfbox.layout.text.Alignment cannot be resolved

The import rst.pdfbox.layout.text.BaseFont cannot be resolved

**Comment by jyf1997** [comment]
@prasser 
I try to import the jar package under lib into the project, and the program will be fine. I use the following command: for / R E: offer jyf arx arx lib% I in (*. jar) do exist% I copy "% i" C: DesUsers FAN ktop New folder.

Another question is, I want to use ARX to read OpenRefine text and encrypt it. Is that possible?

**Comment by prasser** [comment]
Thanks, so this issue is resolved? ARX is not an encryption library and I would need more details to tell you whether or not ARX is what you are looking for. Please create a new issue for discussing this. Thanks, Fabian
