### ISSUE TITLE
how to import by eclipse and run it?

### ISSUE THREAD

**Issue by realRuiGuo** [arx-deidentifier/arx#255]
i import master by import git on eclipse ,but i can not run /gui/main.class,what should i do ?

**Comment by giupardeb** [comment]
Hi @realRuiGuo you can following these steps:

1. fork and clone arx project
2. from eclipse "Checkout projects from Git"

So,
Just create a new project, but in the wizard set as the project directory the directory containing the ARX source. after that the wizard will automatically put all jar files on your classpath. It's important that you remove the swt-*.jars that are not for your platform from the class path (e.g. remove swt for osx and swt for gtk when you are on windows).

**Comment by realRuiGuo** [comment]
thanks，i got it

**Comment by realRuiGuo** [comment]
then，how can i change or redesign UI using gui

**Comment by prasser** [comment]
It's not possible to change ARX's UI using a graphical editor. You have to do it by modifying the code. Best, Fabian
