### ISSUE TITLE
how to get a part of Transformed data(eg:age=60), And perform risk analysis for this part of the data?

### ISSUE THREAD

**Issue by realRuiGuo** [arx-deidentifier/arx#256]

**Comment by prasser** [comment]
See reply to #257 You can do this either (1) without anonymization, when only loading input data, (2) after anonymization, if the required subset has been selected before anonymization.

**Comment by realRuiGuo** [comment]
After anonymization,i want to just analyse a part of output  corresponding to the subset of input.

**Comment by prasser** [comment]
Ok, then you have to select the subset before the anonymization process.

**Comment by realRuiGuo** [comment]
em...,actually i want to analyse the output before select the subset ,because after select the subset , the output will change and decrease in quantity ,can i do this by changing the code?

**Comment by realRuiGuo** [comment]
i want to analyse a part of output before select the subset.

**Comment by realRuiGuo** [comment]
In other words,i want to analyze a subset of the output without changing the existing output to compare it with the output that first selects the subset and then anonymizes. please help me!

**Comment by prasser** [comment]
This is not supported. Please create a feature request.

**Comment by realRuiGuo** [comment]
Ok,thanks.

**Comment by prasser** [comment]
Resolved. Closing.
