### ISSUE TITLE
 how to select subset in output corresponding to the selected input?

### ISSUE THREAD

**Issue by realRuiGuo** [arx-deidentifier/arx#257]

**Comment by realRuiGuo** [comment]
when i use Query selection mode select input data,i can select subset in input ,but i also want to select subset in output corresponding to the selected input.
![image](https://user-images.githubusercontent.com/12027656/55217924-9fdb2c80-523b-11e9-8795-6b72dbfae3a2.png)

left side is input,some raws is unselected,but on the right side ,they are still selected,how can i make right side unselected too,so i can just analyze the selected part.

**Comment by prasser** [comment]
This is only supported, if you select the relevant subset before the anonymization process, the subsets for input and output will then be identical. If you want more flexibility regarding the use of subsets, please open up a new issue ("feature request") and describe the requested feature in detail.

**Comment by prasser** [comment]
No more activity. Closing.
