### ISSUE TITLE
Detect suppressed records in input data

### ISSUE THREAD

**Issue by realRuiGuo** [arx-deidentifier/arx#259]
The first: i run the example29 ,then save the output,i get the output and Risk analysis as below:
 - Output data
   [age, gender, zipcode]
   [<50, female, 81***]
   [<50, male, 81***]
   [>=50, male, 81***]
   [*, *, *]
   [<50, female, 81***]
   [>=50, male, 81***]
   [<50, male, 81***]
 - Risk analysis:
   * Equivalence classes:
     - Average size: 2.0
     - Num classes : 3.0
     - Histogram   :
        [Size: 2, count: 3]
   * Risk estimates:
     - Sample-based measures
       + Average risk     : 0.5
       + Lowest risk      : 0.5
       + Tuples affected  : 1.0
       + Highest risk     : 0.5
       + Tuples affected  : 1.0
       + Sample uniqueness: 0.0
     - Population-based measures
       + Population unqiueness (Zayatz): 0.0
 - Writing data...Done!

The second: i run my code, code and result  as below,the risk is different and wrong,it see [*, *, *] as an equivalence class:
`    public static void main(String[] args) throws IOException {
        
        Data data = Data.create("data/test_anonymized.csv", StandardCharsets.UTF_8, ';');
		// Define hierarchies
		DefaultHierarchy age = Hierarchy.create();
		age.add("34", "<50", "*");
		age.add("45", "<50", "*");
		age.add("66", ">=50", "*");
		age.add("70", ">=50", "*");

		DefaultHierarchy gender = Hierarchy.create();
		gender.add("male", "*");
		gender.add("female", "*");

		// Only excerpts for readability
		DefaultHierarchy zipcode = Hierarchy.create();
		zipcode.add("81667", "8166*", "816**", "81***", "8****", "*****");
		zipcode.add("81675", "8167*", "816**", "81***", "8****", "*****");
		zipcode.add("81925", "8192*", "819**", "81***", "8****", "*****");
		zipcode.add("81931", "8193*", "819**", "81***", "8****", "*****");

		data.getDefinition().setAttributeType("age", age);
		data.getDefinition().setAttributeType("gender", gender);
		data.getDefinition().setAttributeType("zipcode", zipcode);
        // Perform risk analysis
        System.out.println("\n - Input data");
        print(data.getHandle());
        System.out.println("\n - Quasi-identifiers sorted by risk:");
        analyzeAttributes(data.getHandle());
        System.out.println("\n - Risk analysis:");
        analyzeData(data.getHandle());   
          }`
result:
 - Input data
   [age, gender, zipcode]
   [<50, female, 81***]
   [<50, male, 81***]
   [>=50, male, 81***]
   [*, *, *]
   [<50, female, 81***]
   [>=50, male, 81***]
   [<50, male, 81***]
 - Risk analysis:
   * Equivalence classes:
     - Average size: 1.75
     - Num classes : 4.0
     - Histogram   :
        [Size: 1, count: 1]
        [Size: 2, count: 3]
   * Risk estimates:
     - Sample-based measures
       + Average risk     : 0.5714285714285714
       + Lowest risk      : 0.5
       + Tuples affected  : 0.8571428571428571
       + Highest risk     : 1.0
       + Tuples affected  : 0.14285714285714285
       + Sample uniqueness: 0.14285714285714285
     - Population-based measures
       + Population unqiueness (Zayatz): 0.02040816359614952

**Comment by realRuiGuo** [comment]
I want to analyze a subset of the output, As shown above, i export the output and analyse it as input,but it does not work.
How can I achieve this goal?

**Comment by prasser** [comment]
Thanks for reporting this! First of all: this is not a critical issue. The reason for these differences is that ARX does not automatically detect suppressed records in output data. We will add a configuration option to support  this functionality.

**Comment by prasser** [comment]
A fix has been deployed to the branch "outliers". Can you please check? Also, there is a new example (Example58) that reflects your use case.

**Comment by prasser** [comment]
Fix merged. Closing.
