### ISSUE TITLE
[new feature] pseudonymization

### ISSUE THREAD

**Issue by giupardeb** [arx-deidentifier/arx#266]
Hi all guys, I would like to start to implement a new feature that allows us to re-identify a dataset.
What do you think?

**Comment by prasser** [comment]
Hi Guiseppe. Why not. What are your concrete plans?

**Comment by giupardeb** [comment]
I'm thinking an a system of mapping. The system of re-identify can be implemented by saving the mapping between the patient identification number and the pseudonym or by saving the parameters of a reversible mapping function. Obviously the mapping will be save on disk and it can be encrypted with a key. I believe that the mapping between the patient identification number and the pseudonym is not difficult to develop

**Comment by prasser** [comment]
So you want to implement a pseudonymization function (not a process that performs a re-identification attack)? If so, please take a look at the branch "psn". Such a feature is already under development.

**Comment by giupardeb** [comment]
I don't think that what I want is a pseudonymization function. I want implement a re-identification function that allow the user to re-identify dataset creating a mapping file. for example:

I have a dataset X, I apply on X the pseudonymization function Y and getting a dataset Z. At the same time I create a map, that allow me to come back from Z to X.
Furthermore, can you suggest me the start point on branch "psn"?

**Comment by prasser** [comment]
The described process *is* a pseudonymization function. Sorry, the correct branch is "msk" (I think you know it already) not "psn". There is a pseudonymization function implemented which just needs to be extended to produce a mapping table.

**Comment by giupardeb** [comment]
on reflection...you're right! Yes the process that I described above is a pseudonymization function. 
Now I search the implemented pseudonymization function, Thank you so much! :-D

**Comment by giupardeb** [comment]
Hi Fabian, yesterday and today I tried to find the implemented pseudonymisation function, but I didn't find it. Can you give me more information about the file where the function is defined?

**Comment by prasser** [comment]
See "DataMaskingFunctionRandomAlphanumericString" here:

https://github.com/arx-deidentifier/arx/blob/msk/src/main/org/deidentifier/arx/masking/DataMaskingFunction.java

**Comment by giupardeb** [comment]
Great! Thank you!

**Comment by prasser** [comment]
PR in progress. Closing.
