### ISSUE TITLE
[QUESTION] About Snapshot Size

### ISSUE THREAD

**Issue by ronnypeterson** [arx-deidentifier/arx#285]
Hi,

I have worked with Intel SGX which creates a hardware level vault, but has a limit of 128 MB for reasonable performance, in fact around 90 MB.
I'm using ARX and saw in the documentation something like this:

ARXAnonymizer anonymizer = new ARXAnonymizer ();
anonymizer.setSuppressionString ("*");
anonymizer.setMaximumSnapshotSizeDataset (0.2);
anonymizer.setMaximumSnapshotSizeSnapshot (0.2);
anonymizer.setHistorySize (200);
anonymizer.setRemoveOutliers (true);

I ask, for this resource constraint scenario, what parameters could I use?

Greetings,

Ronny

**Comment by prasser** [comment]
Hi,

thanks for your interest in ARX! The smaller you make these parameters, the lower the memory consumption:

anonymizer.setMaximumSnapshotSizeDataset (0.2);
anonymizer.setMaximumSnapshotSizeSnapshot (0.2);
anonymizer.setHistorySize (200);

A value of 0 should be the minimum for all those parameters.

I hope this helps!
Fabian

**Comment by ronnypeterson** [comment]
Thank so much!
