### ISSUE TITLE
API for number of suppressed records in anonymized dataset?

### ISSUE THREAD

**Issue by sonhal** [arx-deidentifier/arx#290]
HI I am just wondering if there is a API in the java lib for extracting information about how many rows have been completely suppressed in the anonymized dataset. Could not seem to find any in the source code or documentation.

Best regards,
Sondre

**Comment by prasser** [comment]
Sorry for the delay in replying. You have several options:

(1) Just count them:

`int suppressed = 0;`
`for (int i = 0; i < handle.getNumRows(); i++) {`
`    if (handle.isOutlier(i)) {`
`    suppressed++;`
`    }`
`}`

(2) Use statistics provided by ARX:

'handle.getStatistics().getEquivalenceClassStatistics().getNumberOfSuppressedRecords()'
