### ISSUE TITLE
Question: where are data transformation methods?

### ISSUE THREAD

**Issue by gonapps** [arx-deidentifier/arx#291]
Hi I am reading ARX source to use libarx and the readme says
> Data transformation with generalization, suppression, microaggregation and top/bottom coding as well as global and local recoding

But i couldn't find related methods or classes.
Where can I found those functionalities?

**Comment by prasser** [comment]
Thanks for your interest in ARX! Please take a look at the examples provided in the package `org.deidentifier.arx.example`. They cover all transformation methods listed above. Best, Fabian
