### ISSUE TITLE
[BUG] Website arx.deidentifier.org is down

### ISSUE THREAD

**Issue by bgaston97** [arx-deidentifier/arx#292]
Pressing the link to http://arx.deidentifier.org/ results in "This site can't be reached". Tried from several different sources and got the same result. Looking to use it as a reference.

**Comment by prasser** [comment]
Works for me. Seems to be a problem on your side...

**Comment by bgaston97** [comment]
I apologize, I tried again out of a 3rd location and was able to connect.  Thanks for checking.
