### ISSUE TITLE
where can I download the previous version such as libarx-3.71-min.jar

### ISSUE THREAD

**Issue by gch35pty** [arx-deidentifier/arx#293]
As the latest version has updated to 3.8.0, where can I download the previous version such as libarx-3.71-min.jar?
For some reasons, I can not build from source file locally. Someone could help me ?

**Comment by arx-deidentifier** [comment]
Hi gch35pty,

thanks for your interest in ARX! Why do you want to download the previous version? We strongly recommend to use the current version of ARX.

Best
Fabian

**Comment by prasser** [comment]
Closing this now. If you have a good reason for using an older version, please create a new issue.
