### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by smoghe-tlx** [arx-deidentifier/arx#297]
**Describe the bug**
When we try to create  org.deidentifier.arx.Data using below approach,it throws error:
Data.create(inputStream, StandardCharsets.UTF_8, ',');

**To Reproduce**
1. Create Data object using inputstream
2. Run the project
3. It throws exception:
java.lang.IllegalArgumentException: Data object is empty!
	at org.deidentifier.arx.DataHandleInput.<init>(DataHandleInput.java:70)
	at org.deidentifier.arx.Data.getHandle(Data.java:579)
	at org.deidentifier.arx.ARXAnonymizer.anonymize(ARXAnonymizer.java:203)

**Expected behavior**
Anonymization should not fail

**Screenshots**
This is using ARX API.

**ARX GUI (please complete the following information):**
NA

**Additional context**

**Comment by prasser** [comment]
Thanks for your interest in ARX and for reporting this issue! Can you please post a minimal code example, so that we can debug this problem?

**Comment by prasser** [comment]
Please also check whether your input stream really provides access to data (e.g. is not closed etc.). Code using our example dataset that fails would be perfect. Best, Fabian

**Comment by smoghe-tlx** [comment]
This was not an issue.So sorry.The input stream was empty
