### ISSUE TITLE
[BUG] Not able to limit number of redaction character to certain limit in HierarchyBuilderRedactionBased

### ISSUE THREAD

**Issue by smoghe-tlx** [arx-deidentifier/arx#298]
**Describe the bug**
Not able to limit number of redaction character to certain limit in HierarchyBuilderRedactionBased

**To Reproduce**
1.Use  HierarchyBuilderRedactionBased API to anonymize ZIpcode.

Suppose you have zip code as "12345".Using below line of code,it is redacting it to *****.
I want it to 123(2 STARS)   or   12(3 STARS)   or   1****
HierarchyBuilderRedactionBased<?> zipBuilder = HierarchyBuilderRedactionBased.create(Order.RIGHT_TO_LEFT,
				Order.RIGHT_TO_LEFT, ' ','*');

**Expected behavior**
Should get some option for desired output

**Screenshots**

**ARX GUI (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 3.7.1]

**Additional context**

**Comment by prasser** [comment]
Thanks for your interest in ARX. AFAICT the code you posted should Do exactly want you want. Can you please post a minimal working example, so that I can look into this. Thanks.

**Comment by prasser** [comment]
Please take a look at the following example showing how the builder is supposed to be used.

```Java
// Test data
String[] data = new String[] {
	"81667",
	"81675",
	"81925",
	"81931",
	"81931"
};

// Create the builder
HierarchyBuilderRedactionBased<?> builder = HierarchyBuilderRedactionBased.create(Order.RIGHT_TO_LEFT,
                                                                            Order.RIGHT_TO_LEFT,
                                                                            ' ', '*');
// Prepare
builder.prepare(data);

// Print resulting hierarchy
for (String[] row : builder.build().getHierarchy()) {
	System.out.println(Arrays.toString(row));
}
```
Result:
```
[81667, 8166*, 816**, 81***, 8****, *****]
[81675, 8167*, 816**, 81***, 8****, *****]
[81925, 8192*, 819**, 81***, 8****, *****]
[81931, 8193*, 819**, 81***, 8****, *****]
[81931, 8193*, 819**, 81***, 8****, *****]
```

If you really think that this is a bug, please provide more information.

**Comment by smoghe-tlx** [comment]
You are right.The code which i am referring would work fine but the final transformed value from arx anonymizer really depends on dataset and its current state of anonymity.
Thanks,closing the ticket.
