### ISSUE TITLE
[BUG] Inconsistent size of GUI elements using Windows' high DPI scaling

### ISSUE THREAD

**Issue by Lumiukko** [arx-deidentifier/arx#304]
**Describtion**
Using the Windows 10 high DPI scaling settings (e.g. for high resolution screens), the SWT elements are being rendered with different sizes (primarily icons and icon bars appear significantly smaller).

**To Reproduce**
1. Go to the windows display options.
2. In the section "Scale and layout" choose "Advanced scaling settings"
3. Activate the option "Let Windows try to fix apps so they're not blurry"
4. Enter a custom scaling size of more than 100% (e.g. 400%, but any value will do. However, the effect is more visible with larger values. Note that you should chose a number that enables you to still use Windows' interface).
5. Click on "Apply".
6. Sign out of your windows account and subsequently back in.
7. Run ARX
8. Observe.

**Expected behavior**
All GUI elements should be scaled up equally.

**Screenshots**
![imgpsh_mobile_save](https://user-images.githubusercontent.com/1744933/76541138-65d25d00-6483-11ea-8e81-4e26c2c86d29.jpg)

**ARX GUI (please complete the following information):**
 - OS: Windows 10
 - Version: 3.8.0

**Additional context**
- This bug should not be relevant to most users, as it only appears using the aforementioned scaling settings in Windows.
- The issue may have to do with a deprecated version of SWT.

**Comment by prasser** [comment]
Please try the following branch, which uses a more recent version of SWT:

https://github.com/arx-deidentifier/arx/tree/swt-4-7-2

Does this change anything?

**Comment by prasser** [comment]
Ping!

**Comment by Lumiukko** [comment]
Unfortunately the **swt-4-7-2** branch did not resolve the issue.
The screenshots below are made with this branch.

Note: While the scaling of 400% is rather extreme, it showcases nicely which elements scale properly and which do not.

![Screenshot 2020-06-08 11 38 23](https://user-images.githubusercontent.com/1744933/84016569-c3405200-a97d-11ea-8234-6471eb7eb476.png)
![Screenshot 2020-06-08 11 39 24](https://user-images.githubusercontent.com/1744933/84016572-c3d8e880-a97d-11ea-9a9f-8e1b5bd98fe2.png)
![Screenshot 2020-06-08 11 40 03](https://user-images.githubusercontent.com/1744933/84016575-c4717f00-a97d-11ea-9de9-62046fd417ad.png)
![Screenshot 2020-06-08 11 41 11](https://user-images.githubusercontent.com/1744933/84016577-c50a1580-a97d-11ea-923a-7cc1b9ce620d.png)

**Comment by prasser** [comment]
This does look significantly better than your initial screenshot created with ARX's master branch. Are you sure that this branch doesn't improve anything? :) Can you maybe create a more detailed comparison and also check all views and menu's of ARX to see where problems remain. I think that the few remaining glitches need to be fixed by changing ARX's code...

**Comment by prasser** [comment]
@Lumiukko The branch swt-4-7-2 has just been updated. Please check it again and see whether it further improves anything. Several swt-related libraries have been moved to lib/eclipse, so you will need to update your classpath.

**Comment by prasser** [comment]
This bug has been fixed with recent updates to SWT components. Scaling now looks fine when using Windows' standard scaling options. Some issues with custom scaling factors available through the advanced settings persist, but even Microsoft discourages its users from using this feature ("not recommended"). Closing this issue.
