### ISSUE TITLE
Automatically select new nodes in hierarchy wizard

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#305]
When using the Hierarchy wizard to create a hierarchy for ratio or ordinal scales a newly added node (created by clinking "Add after", "Add before" or "Add new level") should be selected by default on creation.

**Comment by prasser** [comment]
ARX is an open source project and we are happy about contributions. :)

**Comment by prasser** [comment]
Implemented in commit b7b5af4. Please test. Closing.
