### ISSUE TITLE
[BUG] Unable to load .deid when working with column-names containing blanks

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#307]
When importing the follwing data to an project:

> "a "
> 1
> 2
> 3

...ARX will save the column name in two different ways to the .deid file.

- When writing the data (contained in "data/input.csv") the column name is trimed (the trailing blank is removed.)
- Within the definition (contained in "input/definition.xml" / "output/definition.xml") the trailing blank ist not removed.

When reloading the .deid file to ARX this will result in an exception:
> java.lang.IllegalArgumentException: Unknown attribute type 'null'
> 	at org.deidentifier.arx.gui.resources.Resources.getImage(Unknown Source)
> 	at org.deidentifier.arx.gui.view.impl.common.ViewData.updateHeaderImage(Unknown Source)
> 	at org.deidentifier.arx.gui.view.impl.common.ViewDataInput.update(Unknown Source)
> 	at org.deidentifier.arx.gui.Controller.update(Unknown Source)
> 	at org.deidentifier.arx.gui.Controller.actionOpenProject(Unknown Source)
> 	at org.deidentifier.arx.gui.Controller.actionMenuFileOpen(Unknown Source)
> 	at org.deidentifier.arx.gui.view.impl.MainWindow$24.action(Unknown Source)
> 	at org.deidentifier.arx.gui.view.impl.MainMenu$1.widgetSelected(Unknown Source)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
> 	at org.deidentifier.arx.gui.Main.main(Unknown Source)
> 	at org.deidentifier.arx.gui.Main.main(Unknown Source)

Example: [test_bug.zip](https://github.com/arx-deidentifier/arx/files/4388400/test_bug.zip)

**Comment by prasser** [comment]
Thanks for reporting this. This is a complicated bug to fix. Can you please check whether the branch "bugfix-univocity" fixes this for you? In general, it will be hard to fix this in a backwards-compatible manner, unfortunately.

**Comment by prasser** [comment]
BTW: This issue has to do with blanks within quoted values. This is quite Rare, fortunately.

**Comment by srcds** [comment]
Thanks for the quick response! Using the "bugfix-univocity" branch I created a new project using the input metnioned in my inital post (with "a " as column name) . After saving the project I am still not able to reload it to the GUI. However, now I receive the message "Invalid internale state. Numbers of records don't match" instead of stack trace.
![error_message](https://user-images.githubusercontent.com/9593020/78234968-39d15700-74d8-11ea-9539-e263fe80dfca.PNG)

**Comment by prasser** [comment]
Thanks, good catch! Please try again.

**Comment by srcds** [comment]
Now it works flawlessly! Thanks
