### ISSUE TITLE
Getting 'app cannot be opened' error with OSX installer

### ISSUE THREAD

**Issue by JingtongNg** [arx-deidentifier/arx#311]
Hi,

I am having some issues running the most recent OSX installer and keep getting an "app cannot be opened" message. I have tried changing some of the text edit files into executables but it still is not working. I'm not sure if it's a problem exclusive to my computer so any insight would be appreciated.

**Comment by prasser** [comment]
Thanks for your interest in ARX and for reporting this. Can you please provide more details? Which version of ARX are you using? Can you post a screenshot of the error message? Etc. Thanks!

**Comment by JingtongNg** [comment]
I am using the most recent 3.8.0 OSX 64-bit installer and I can download it but the installer can't be opened. I have attached an image. Thank you for your help 

![image](https://user-images.githubusercontent.com/49790192/79490429-c0c41a80-8014-11ea-8b5a-2f5f99e74947.png)

**Comment by prasser** [comment]
Does this help: https://superuser.com/questions/1345755/how-to-fix-the-application-cant-be-opened-on-mac

? 
--
Univ.-Prof. Dr. Fabian Prasser

Leiter AG Medizininformatik
Berlin Institute of Health
Charité - Universitätsmedizin Berlin
Campus Mitte
Charitéplatz 1
10117 Berlin

Tel: +49 (0)30 450 528781

Besucheradresse:
Campus Mitte
Rahel-Hirsch-Weg 5 (Charité Campus-Klinik), Ebene 03
Raum: 2711 03 014

**Comment by JingtongNg** [comment]
I did try to make the text files executable but when I try to launch it I get this error
![image](https://user-images.githubusercontent.com/49790192/79493238-17cbee80-8019-11ea-9016-a5b3f0a2c191.png)

**Comment by prasser** [comment]
I think that this might be a problem with your Mac. Does this help: https://support.apple.com/en-us/HT208050

?

**Comment by fredchettouh** [comment]
@prasser I had the same issue. I so far tried two things:

1. I disabled the Mac Gate Keeper to allow apps "from anywhere"--> did not help
2. I made the file an executable--> also did not help. 

Would you have any other suggestions? Thanks

**Comment by prasser** [comment]
This might be related to this issue: 

https://github.com/arx-deidentifier/arx/issues/315

We're working on it. A fix will be released with the next version.
