### ISSUE TITLE
Attribute and Dataset Level Utility Metrics

### ISSUE THREAD

**Issue by firmai** [arx-deidentifier/arx#314]
Hi. thanks for the package and your great research contributions. I am interested in calcualting dataset and attribute quality measures in Python. It is a project I call DataGene. I have been intruiged by the 8 methods you have made available in this domain; non-uniform privacy, discernibility etc. 

Do you perhaps know if there is already any python versioning of these attributes or something along similar lines. Looking very mich forward to your response. Best, Derek .

**Comment by prasser** [comment]
Hi Derek,

thanks for your interest in ARX and for your kind words. I'm not aware of any implementation in Python. Should you think about porting the code of ARX (or at least using it as an inspiration), please note that we have two implementations of each model. You can find the first implementation in this package:

https://github.com/arx-deidentifier/arx/tree/master/src/main/org/deidentifier/arx/metric

and the second implementation here:

https://github.com/arx-deidentifier/arx/tree/master/src/main/org/deidentifier/arx/aggregates/quality

I think that the second implementation is much easier to understand, and is probably more suitable for your purpose.

Best
Fabian

**Comment by firmai** [comment]
Thank you so much, I am going to try and port it as best I can in the coming few months. Will let you know once I have done so for you to test it.
