### ISSUE TITLE
Is it usable for preventing stylometry analysis?

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [arx-deidentifier/arx#330]
Hi!

I'm quite interested in Arx but cannot understand one thing. Is it possible to use somehow Arx for preventing stylometry analysis? My use case is: I have a lot of messages (emails, chat messages) and I want to transform them somehow, that deanonymization by their style will be very hard/impossible.

Stylometry analysis link: https://en.wikipedia.org/wiki/Stylometry

If you know any such software - let me know :)

Thank you!

**Comment by arx-deidentifier** [comment]
Thanks for your interest in ARX. However, the software has been designed for protecting structured data only, and hence can't be used for preventing stylometry analysis.
