### ISSUE TITLE
Histograms in the Risk Analysis perpective

### ISSUE THREAD

**Issue by igorlemes** [arx-deidentifier/arx#335]
I understand that ARX has a contextual help button and we used it, but me and my colleagues could not understand the histogram in the Risk Analysis perspective. The blue histogram we understood, but the red one makes no sense.
Maybe it is just something we didn't understand or maybe it is a bug.

**Comment by prasser** [comment]
Thanks for your interest in ARX and sorry for the late response. The red histogramjust shows the cumulative distribution of risk (while risk is shown by the blue histogram). At a certain risk threshold it hence shows the fraction of records with a risk that is equal to or lower than the threshold. Does this answer your question?

**Comment by prasser** [comment]
Closing due to lack of response.
