### ISSUE TITLE
[Question] Using DP on datasets with hundreds of columns

### ISSUE THREAD

**Issue by sasvaritoni** [arx-deidentifier/arx#339]
Hi,

I am experimenting with using the Differential Privacy model on a dataset with >200 features, and usually all of the data rows are masked out in the output.

Thinking about how the SafePub method works, I am suspecting that it is not really meant to be used for so many features/columns: even if I define the generalization hierarchies for numbers so that I have just 2 possible values (e.g. positive / negative), due to the number of columns it may still result in a very high number of possible variations (2^200), making it hard to "hide" a specific row eventually (unless the # of rows is really huge).

Am I wrong with this? Could it be used even for hundreds of features?

Thx,
Antal

**Comment by prasser** [comment]
Hi Antal,

thanks for your interest in ARX. The DP mechanism in ARX is based on the k-anonymity privacy model. Hence all limitations applying to this model also apply to the DP mechanism. One of these limitations is that it is not well suited for high-dimensional data. The number of columns should, roughly, be significantly lower than 50.

Best
Fabian

**Comment by sasvaritoni** [comment]
Thank you very much, Fabian.
This makes it clear.

Best Regards, 
Antal

**Comment by TurbineCoop** [comment]
Hi,
I tried DP model with the Dataset examples provided by ARX, and all of the data rows are masked out in the output.
Also, it seems like some data are removed in the input when I apply the DP model (900 rows to 650 rows).
Here, there is 5 columns in the dataset, so I don't really see the correlation with your remarks concerning the number of columns.
Can you help ?
Many thanks,
Best,
Elsa

**Comment by prasser** [comment]
Hi Elisa,

thanks for your interest in ARX. There are many potential influencing factors, e.g. data distribution, the generalization hierarchies configured and the parameters used to run the DP algorithm. Can you provide us with more information, or maybe even a working example (e.g. an ARX project file)?

Best
Fabian
