### ISSUE TITLE
Fail to build with Ant on OS X

### ISSUE THREAD

**Issue by anirbanbasu** [arx-deidentifier/arx#34]
I am trying to build the project using Ant (version 1.9.4 compiled on April 29 2014) on OS X 10.10.1 (Yosemite) and here's what I get from the compile task (followed by 30 errors due to the lack of packages.

`
[javac] /Users/abasu/github/arx/src/gui/org/deidentifier/arx/gui/view/impl/menu/DialogProperties.java:31: error: package de.linearbits.preferences does not exist
`

Am I missing something?

**Comment by prasser** [comment]
Dear Anirban,

thanks for your interest in ARX!

You are not missing something, the Ant build file was lacking a reference to a library required for building. This is fixed now in our master.

Please note that our current development process does not necessarily guarantee that our master branch passes all unit tests or can be built with Ant. It should be possible to compile it at any time, however, but not necessarily with Ant.

If you want to use a version of ARX that has been tested by us, you should stick with the current release version. The master branch may provide plenty of new features, though, and we are happy about anybody that uses it and provides us with bug reports.

Best regards
Fabian

**Comment by anirbanbasu** [comment]
Hi Fabian,

Thanks very much for your message and thanks for fixing the issue.

Right, I was a bit curious about any new features in the master branch. I did download the 2.3.2 release and I have started using it.

Best regards,
Anirban
