### ISSUE TITLE
[FEATURE] Default file name of new projects

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#346]
When creating a new project ARX requires the user to enter a project name (e.g. "Anon-Test1").
When saving the new project for the first time (using File > Save project -or- File > Save project as..) the software does not suggest the name of the project as the default file name (i.e. "Anony-Test1.deid"). This feature could further increase usability.

**Comment by prasser** [comment]
Sounds like a good idea. A method would need to be implemented to automatically derive a file name that is valid on the current platform. Assigning to @srcds

**Comment by srcds** [comment]
Another feature related to this topic is the following:

When exporting hierarchies using the ARX GUI (File > Export hierarchy...) it would be useful if ARX suggests a default file name.

One potential pattern (which would also meet the programming examples included in the project) could be:
**<project_name>\_hierarchy\_<attribute_name>.csv**

E.g.
texas_hierarchy_TOTAL_CHARGES
... for a attribute named _TOTAL\_CHARGES_ in the project _texas_

**Comment by prasser** [comment]
Implemented in the commit referenced above.
