### ISSUE TITLE
[FEATURE] Symbol indicating "hierarchy status" of attribute

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#347]
For working with high-dimensional datasets, it would be useful to add a symbol to the attribute headers in the Configuration Perspective which indicates whether a hierarchy is defined for the attribute. This feature would even be more valuable if it could also indicate whether the defined hierarchy is complete and can be used for the anonymization (or if it is missing certain values).

In the attached example a hierarchy is defined for the attributes f, h and i. The hierarchy of h is incomplete.
![hierarchy](https://user-images.githubusercontent.com/9593020/104177889-ca46ab80-5409-11eb-8ee9-ac8a76fa668d.PNG)

**Comment by prasser** [comment]
Great suggestion, but of course this needs to be assigned to @srcds ...

**Comment by prasser** [comment]
There is also a Tab "Attribute metadata" on the rights side of the configuration perspective. It lists all attributes and could be extended to include this information. This would probably provide an even better overview (and will be easier to implement).

**Comment by prasser** [comment]
Implemented with the commit referenced above.
