### ISSUE TITLE
Local Recoding should return locally-optimal results?

### ISSUE THREAD

**Issue by a785236** [arx-deidentifier/arx#350]
**Is your feature request related to a problem? Please describe.**
Local recoding does not optimize every equivalence class to the extent possible. For example,

1. Change line 53 of Example38.java to read: data.add("34", "male", "81931");
2. Run the new version of Example38
3. The result of the local recoding is:
```
[age, gender, zipcode]
[<50, male, 819**]
[*, *, *****]
[>=50, male, 819**]
[*, female, 81931]
[*, *, *****]
[*, female, 81931]
[>=50, male, 819**]
[<50, male, 819**]
```

Observe that the following refinement of the above result would also satisfy 2-anonymity:
```
[age, gender, zipcode]
[<50, male, 81931]
[*, *, *****]
[>=50, male, 819**]
[*, female, 81931]
[*, *, *****]
[*, female, 81931]
[>=50, male, 819**]
[<50, male, 81931]
```

Note that this is not only a failure to find a globally-optimal solution (which I would not at all expect), but a failure to find a locally-optimal solution.

**Describe the solution you'd like**
I would expect the result of local recoding to be locally optimal. That is, it should not be possible to generalize any records less (while keeping other records unchanged) and still satisfy k-anonymity.

[Sorry for the many edits. Just trying to fix the Markdown.]

**Comment by prasser** [comment]
Thanks for your interest in ARX and your question! Feedback:

(1) The local recoding algorithm in ARX has been designed to generically support a wide range of privacy models and data quality/utility models. Not for all models, generalizing all records as much as possible might necessarily be the "best" solution.

(2) The algorithm can be influenced by a range of runtime configuration parameters and Example38 uses a somewhat outdated setting. To achieve the desired result, please use the following parameters:

Line 96 - change to: `config.setQualityModel(Metric.createLossMetric(0d));`
Line 114 - change to: `result.optimizeIterativeFast(optimum, 1d / data.getHandle().getNumRows());`

**Comment by a785236** [comment]
Thank you for the response. Will the suggested configuration always result in (what I called) a locally-optimal solution? If not, is there some configuration that will? 

(As I'm sure you know, the documentation says little about local recoding, which is why I'm trying to figure out how it works based on the example code. I understand it's a somewhat newer feature.)

**Comment by prasser** [comment]
The algorithm is described in detail here:

https://onlinelibrary.wiley.com/doi/full/10.1002/spe.2812

It performs clustering and generalization within a single process and I'm not aware of a proof of (local) optimality.

The various parameters basically control a trade-off between efficiency/scalability and optimality (i.e. output data quality/utility). What I can tell is that the configuration currently used in Example38 optimizes more towards speed while the configuration I suggested above optimizes towards maximum output data quality/utility. Hence it can be expected that it provides the "most optimal" ;) output. There is no known guarantee, however, that it will be locally optimal.

Regarding documentation: it is true that this feature is not well documented. It is a bit different to document, however, as it involves an interplay of various methods provided by ARX. Hence there is no single point within ARX's code where it can be documented. It probably makes sense to change Example38 to use the suggested default configuraiton and not a special case optimized towards speed.

**Comment by a785236** [comment]
Thank you for the pointer and the advice.
