### ISSUE TITLE
[BUG] Unable to replace hierarchies after using the hierarchy wizard

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#358]
Once the hierarchy wizard was used to create a hierarchy for an attribute, this hierarchy cannot be properly replaced with an imported hierarchy. Although importing the new hierarchy does not result in any errors and the imported hierarchy is correctly displayed in the GUI, the anonymization process still utilizes the old hierarchy which was created by the wizard. 

Tested on ARX 3.9.0 and on ARX 3.8.0 (Windows).

Steps for reproduction:

1.  Create new project and import data, E.g.:
> Attribute_1
A
B
C
D

2. Create a hierarchy for Attribute_1 using the wizard. I used the “Use masking” option and clicked through the wizard resulting in the following hierarchy: 
>A;*
B;*
C;*
D;*

3. Import a new hierarchy for Attribute_1. E.g. the following (manually created using a notepad):
> A;low;*
B;low;*
C;high;*
D;high;*

4. Set 2-Anonymity; Make Attribute_1 a Quasi-identifier; Anonymize.

Looking on the result reveals, that ARX won’t use the imported hierarchy but the one created with the wizard.

The .deid project file of this example as well as the raw dummy data and dummy hierarchy is attached in the .zip file.
[ExampleHierarchyBug.zip](https://github.com/arx-deidentifier/arx/files/6694655/ExampleHierarchyBug.zip)

**Comment by srcds** [comment]
It seems like the problem is caused by not removing the hierarchyBuilder.

Once a hierarchyBuilder for a certain attribute is created (using the wizard) it can only be replaced by a new hierarchyBuilder (using the wizard) or it can be removed using the GUI (right click on the hierarchy in the "Data transformation" tab and select "Clear"). When using the "Import Hierarchy .." feature, however, the old hierarchyBuilder is neither deleted nor replaced. 

A simple fix could be to call 
`model.getInputConfig().removeHierarchyBuilder(attr);`
in the method actionMenuFileImportHierarchy() of the class org.deidentifier.arx.gui.Controller.

**Comment by prasser** [comment]
Fixed
