### ISSUE TITLE
Problems by importing data from a PostgreSQL Database[BUG]

### ISSUE THREAD

**Issue by BladeRunner902** [arx-deidentifier/arx#360]
Hello,

I am trying to import data from a PostgreSQL Database. So i klick the button "import data", chose "database" and then "PostgreSQL" and fill in the grid. After that "successfully connected to database" shows up. When i am now klicking on "Next" the program hangs up with the error message "no respond". 
What can i do?

**Comment by prasser** [comment]
Hi BladeRunner,

thanks for your interest in ARX and for reporting this. Would you be able to help us with debugging this? First, a screen shot of the window and the error message would be great. Second, would you maybe be able to run ARX from source?

Thanks
Fabian

**Comment by BladeRunner902** [comment]
Hello,

Error messages:

In the first picture there is "Keine Rückmeldung" which means "no respond"

![ARX Fehlermeldung](https://user-images.githubusercontent.com/87760481/126939517-5b2ac29a-9e77-43bd-a9ef-b34ed255b619.PNG)
![ARX Fehlermeldung 2](https://user-images.githubusercontent.com/87760481/126939567-459e1f9e-88f0-468a-8270-dcfa570b3495.PNG)

**Comment by prasser** [comment]
Thanks, again. This is clearly an unexpected error. Two follow-up questions:

(1) How big is the database that you try to connect to?
(2) Would you be able to run ARX from source?

**Comment by prasser** [comment]
Closing due to a lack of feedback. Please re-open if you can provide further information.
