### ISSUE TITLE
[BUG] Incorrect amount of generalization levels being generated for interval based hierarchies

### ISSUE THREAD

**Issue by Kamskie** [arx-deidentifier/arx#362]
**Describe the bug**
Hi,

I think I may have found a bug but I'm not sure if this is intended behaviour or not.

This bug seems to occur whenever all values for a generalization level are identical. If they are all identical, the next generalization level will not be generated.

**To Reproduce**
For example, I created a hierarchy with the wizard as seen below:

![hierarchybuilder](https://user-images.githubusercontent.com/66316077/136044618-9efa8a2c-db25-4e2c-bf98-d95012e841d2.PNG)

and I have imported a csv with a single column called age with values 1,5,7. To my understanding this should generate 4 levels with those levels being: "[0, 5[", "[0,10[", "[0, 20[", "*". Instead I get the following:

![hierarchyview](https://user-images.githubusercontent.com/66316077/136045939-1624b60e-854d-4760-b68a-a15efd91bded.PNG)

As you can see here there are only two generalization levels, whereas to my understanding there should be four.

Doing some further testing I've managed to recreate this with a few different pieces of data and from what I could tell the hierarchy builder stops generating new levels whenever it generates a generalization level where all values are identical, resulting in less generalization levels being created than expected.

I built a hierarchy builder using the code below.

```
public static void BuildIntHier() throws IOException {
		Double lower = 0.0d;
		Double upper = Double.MAX_VALUE;
		HierarchyBuilderIntervalBased<Double> b = HierarchyBuilderIntervalBased.create(DataType.DECIMAL, new 
                Range<Double>(lower, lower, Double.MIN_VALUE/4), new Range<Double>(upper, upper, Double.MAX_VALUE));
				
		b.setAggregateFunction(DataType.DECIMAL.createAggregate().createIntervalFunction(true, false));
		b.addInterval(0d, 5.0d);
		
		b.getLevel(0).addGroup(2);
		b.getLevel(1).addGroup(2);
		b.getLevel(2).addGroup(2);
		b.getLevel(3).addGroup(2);
		
		b.save("builders/age10.ahs");
	}
```

But when I built it using the same data with 1,5,7, I got the same result.

![hierarchyfile](https://user-images.githubusercontent.com/66316077/136048597-abdfc881-75a3-47c1-8d73-fba8f5ece4c8.PNG)

**Expected behavior**
To my understanding, when you define the hierarchy in the hierarchy wizard or using the HierarchyBuilder class, there should be a generalization level generated for every level you create plus one extra level containing "*" instead of stopping whenever it generates a generalization level where all values are identical.

**ARX GUI (please complete the following information):**
 - OS: Windows 10
 - Version 3.9.0

**Additional context**
Like I said I'm not sure if this is intentional or not so please don't hesitate to correct me if I'm wrong.

**Comment by prasser** [comment]
Thanks, again. Just one final comment:

> I would say there would be some sense in adding the extra levels as they would offer a wider range for the generalization therefore further obscuring the original value, however it is definitely questionable how much extra value this would add.

Please note that this can also be achieved by editing the tabular view of the hierarchy in ARX's main window. Here you can add additional levels manually, and if a level consists of just one value this can be done with very little effort.
