### ISSUE TITLE
Add "Quarter/Year" to hierarchy wizard for dates

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#364]
When creating a hierarchy for dates using the option "Quarter of year", only the quarter but not the year is listed in the resulting hierarchy. As this also applies for "Month of year" (where only the month is listed), I guess this is not a bug. However, it would be useful to introduce the additional option “Quarter/Year” (similar to “Month/Year”), where both, the quarter, and the year, are considered in the generated hierarchy.

**Comment by prasser** [comment]
Assigned to @srcds as this is a good oppportunity to better get to know ARX.

**Comment by idhamari** [comment]
The code can be found in this [commit](https://github.com/ia-dev/arx/commit/145e39a26b3e0e99623f1ebc7cd3c6b983ed165f).

**Comment by prasser** [comment]
Resolved
