### ISSUE TITLE
Remove dynamic captions of checkboxes in settings dialog

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#367]
In the settings dialog there are several binary options which are controlled via ticking or unticking checkboxes. The caption right to the checkbox changes between “Yes”/”No” depending on whether the option is selected or not. I find this highly confusing.

I wanted to configure a project in such a way that all attributes of suppressed records were removed. Looking at the Transformation tab, I thought this behavior was already configured:
![grafik](https://user-images.githubusercontent.com/9593020/143791220-4b1475a6-69e1-414b-aa89-037985fb0202.png)

In my mind, the default for the second and third option was “Yes” and the non-default “No” must be selected manually by ticking it. As the anonymization was not removing all attributes, I revisited the options dialog and realized that the captions of the checkboxes change depending on whether they are ticked:
![grafik](https://user-images.githubusercontent.com/9593020/143791229-6d267169-d186-4a69-a996-812372433e80.png)
The problem: a “Unticked No” can be interpreted the same way as a “Ticked Yes”. I would strongly suggest changing the caption of the checkboxes to a static “Yes” or remove the caption completely. This change is easy to implement and I can't think of any disadvantages.

**Comment by idhamari** [comment]
Captions are removed. I will create a pull request for this soon when the solution is approved.

 ![Screenshot from 2021-12-03 08-48-30](https://user-images.githubusercontent.com/28802516/144566325-3494fe07-dfdb-4b06-b089-52f6d68e14d3.png).

Some details: 

The code for this part can be found in [createTabTransformation](https://github.com/arx-deidentifier/arx/blob/204214fb1a4c56da0fcc85866b69d8bf60452ccd/src/gui/org/deidentifier/arx/gui/view/impl/menu/DialogProperties.java#L303) function. This function uses import de.linearbits.preferences.PreferencesDialog; which is part of  [swtpreferences](https://github.com/arx-deidentifier/arx/blob/204214fb1a4c56da0fcc85866b69d8bf60452ccd/lib/ant/swtpreferences/swtpreferences-0.0.1.jar) library. The source code for this library is not provided in arx, it is provided [here](https://github.com/prasser/swtpreferences).

**Comment by idhamari** [comment]
This issue is fixed in this [commit](https://github.com/iaBIH/swtpreferences/commit/c5aa9d012cb58e07b5794e0435fa50a6d79aad17)

**Comment by prasser** [comment]
Fix commit
