### ISSUE TITLE
Changing transformation model from global to local

### ISSUE THREAD

**Issue by paoloalb** [arx-deidentifier/arx#369]
Hello,
I am trying to use the ARX api in a Scala project. From the graphical interface I found that it is possible to set the transformation model to use a local transformation instead of global one:
![image](https://user-images.githubusercontent.com/29626380/144019498-24178154-6744-424f-a150-d4fe756e9584.png)

I would like to be able to change this setting via the arx api in my code, but I was not able to find a way by reading the documentation

**Comment by srcds** [comment]
Hey, the ARX source code includes several examples of how to use the API. Example38.java illustrates how to use local recoding. Perhaps this will help you.
https://github.com/arx-deidentifier/arx/blob/master/src/example/org/deidentifier/arx/examples/Example38.java

**Comment by paoloalb** [comment]
Ok i see, thank you very much for the help!

**Comment by prasser** [comment]
Just a hint. Take particular note of the following two lines of code in the example:

        config.setSuppressionLimit(1d);
        config.setQualityModel(Metric.createLossMetric(0d));
