### ISSUE TITLE
[FEATURE] Check completeness of hierarchies during import

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#370]
When importing generalization hierarchies for multiple attributes it can easily happen to confuse different attributes and hierarchy files. 

Example:

- Start ARX and open the "example.deid" project provided as an example in the "data" folder (https://github.com/arx-deidentifier/arx/blob/master/data/example.deid)
- Click on the column “occupation” and click on “File -> Import hierarchy”
- Now we simulate a user error by selecting the hierarchy file “adult_hierarchy_workclass.csv” (https://github.com/arx-deidentifier/arx/blob/master/data/adult_hierarchy_workclass.csv) instead of the hierarchy for occupation (I think it can happen quite fast to confuse them)
- Complete the import 
- When you try to anonymize the dataset the following message will appear:
![grafik](https://user-images.githubusercontent.com/9593020/145221767-8d620735-14b7-4b7a-975a-865d8e7ffe16.png)

Now the user realizes that he/she might have made a mistake during importing the hierarchy. However, now, the old hierarchy for the attribute is already overwritten and lost.
It would be nice if ARX displays a Warning when you want to import an incomplete hierarchy during the import.

E.g.:
____________________________
Attention

The hierarchy you are about to import does not cover the full range of the attribute "occupation": hierarchy does not contain a transformation rule  for value "Sales"

Continue with import?

[Yes]  [No]
___________________________

This request is related to #347

**Comment by prasser** [comment]
Implemented. Closing.
