### ISSUE TITLE
[FEATURE] Could you make the help window non-modal?

### ISSUE THREAD

**Issue by p-vernaeckt** [arx-deidentifier/arx#376]
Hi Arx devs.

This is not really a feature nor a bug: could you make the help window non modal so we can keep it open while using the app?

Thanks!

**Comment by prasser** [comment]
Thanks, sounds like a good idea. We will put this on our TODO list. As a workaround, you can also open the help in the browser and use it side-by-side:

https://arx.deidentifier.org/anonymization-tool/

**Comment by prasser** [comment]
Could be something for @srcds or @idhamari

**Comment by prasser** [comment]
Thanks again for the suggestion. This is now implemented in the current main branch. The dialog will stay modal by default, but there is now an option in the settings dialog to make it modeless.
