### ISSUE TITLE
[BUG] Setting max search space size doesn't work

### ISSUE THREAD

**Issue by prasser** [arx-deidentifier/arx#386]
**Describe the bug**

I get the following message when trying to anonymize a dataset with ~900.000 (global) transformations, although I set the limit to 1.000.000 in the settings dialog:

![image](https://user-images.githubusercontent.com/4058833/172431202-a3b16fd9-59a1-4087-90e9-30583839446c.png)

**Comment by idhamari** [comment]
A sample dataset to reproduce the problem is the [American Community Survey (ACS)](https://www.census.gov/programs-surveys/acs). The CSV file can be downloaded from [here](https://github.com/arx-deidentifier/genetic-benchmark/blob/master/data/ss13acs_int.csv)

**Comment by prasser** [comment]
I don't think that this is really a good example. First, an example for reproducing this would need a dataset + hierarchies. Second, the standard configuration that we use for SS13ACS consists of 34131947028480 (global) transformations. This is much larger than 2^31-1 (=2147483647) and ARX doesn't support optimal search for spaces consisting of more than 2^31 (global) transformations for other reasons.
