### ISSUE TITLE
QueryBuilder crashes with very large dataset

### ISSUE THREAD

**Issue by lautenschlaeger** [arx-deidentifier/arx#39]
Dataset (https://db-ip.com/db/download/city) approx. 5 million tupels 

Working query: 'Column #2'  = 'value' 

Exception below when simply adding OR to the above statement

Exception in thread "Thread-8" java.lang.NullPointerException
     at 
org.deidentifier.arx.gui.view.impl.menu.DialogQuery$1.run(DialogQuery.java:79)
     at java.lang.Thread.run(Unknown Source)

**Comment by prasser** [comment]
Thanks for reporting this issue. We fixed this bug in our current master.
