### ISSUE TITLE
[BUG] Can't deselect all after first page

### ISSUE THREAD

**Issue by ZachHaber** [arx-deidentifier/arx#399]
**Describe the bug**
When selecting "Columns" in the "Import Data" process, Deselect/Select All apply to only the first page.

**To Reproduce**
Import a dataset with over 100 columns.

On the "Columns" page of the "Import Data" step, go to page 2.

Right click and press "Deselect All", page 2 hasn't changed, page 1 has.

**Expected behavior**
Either the deselect all/ select all should apply to only the current page you are on,
Or it should apply to all pages regardless of which page you are on.

**Screenshots**
![image](https://user-images.githubusercontent.com/19843782/186205562-d8c4ae2a-8a07-4607-9eb4-3115d7aa29a1.png)

**ARX GUI (please complete the following information):**
 - OS: Windows 10 (Version	10.0.19044 Build 19044)
 - Version 3.9.0

**Comment by prasser** [comment]
Thanks a lot for reporting this bug. We will fix this.

**Comment by prasser** [comment]
Should be fixed by commit 9c95526790ad8689a28320a44ef68ec4fcd33ede. If not, please re-open.
