### ISSUE TITLE
[BUG] Deselect All creates an invalid state

### ISSUE THREAD

**Issue by ZachHaber** [arx-deidentifier/arx#400]
**Describe the bug**
If you use Deselect All to deselect all columns, it prevents you from moving on to the next step even after selecting a column.

In addition, if you deselect all manually (one at a time), you can still move forward to the next step, but there's an error in the preview.

**To Reproduce**

1. Import data with < 100 columns (#399)
2. Move to the "Columns" Step
2. Right click and use "Deselect All"
3. Right click a column and select it
4. Observe that you still can't move to the next page
5. To continue, past this bugged state, you have to go back a step to the "CSV" step
6. Then go to the "Columns" step again
7. Observe that the Next button is now enabled again

______

For the error state, you can do the same steps as before, but after step 6:
1. disable the column you enabled
2. press Next
3. Observe the error state

**Expected behavior**
I expect that you shouldn't be able to move forward when there are no selected columns regardless of how they are deselected.

In addition, if you select a column again, you should be able to move forward.

**Screenshots**
Before using Deselect All
![image](https://user-images.githubusercontent.com/19843782/186206726-ee17b94b-f334-4577-a062-4de803ed40ee.png)
After using Deselect All
![image](https://user-images.githubusercontent.com/19843782/186206804-08667949-9159-41a3-8b97-79420e61a61c.png)
After Selecting a column
![image](https://user-images.githubusercontent.com/19843782/186206881-1c67a53b-55a7-482e-86ad-40ab39bb1c00.png)

____

After deselecting all columns manually and moving to the next step:
![image](https://user-images.githubusercontent.com/19843782/186207574-476999b3-a0c8-458e-b4ed-bfd6b0d939a9.png)

**ARX GUI (please complete the following information):**
 - OS: Windows 10 (Version 10.0.19044 Build 19044)
 - Version 3.9.0

**Comment by prasser** [comment]
Thanks a lot for reporting this bug. We will fix this.

**Comment by prasser** [comment]
Should be fixed in commit 6275841a6663f279ba5a149f16849facd5a9c82e. If not, please re-open.
