### ISSUE TITLE
[FEATURE] When double clicking a slider/input to edit, it should always select all text

### ISSUE THREAD

**Issue by ZachHaber** [arx-deidentifier/arx#402]
**Is your feature request related to a problem? Please describe.**
When an input dialog pops up to change a value, they often don't have the previous value selected, so you have to use `ctrl+a` to select all in order to change it to what you want. Currently in many of these inputs, the cursor is at the start of the value, where you have to move it in order to change what you want.

**Describe the solution you'd like**
When an input dialog pops up, the cursor should be selecting the whole value to make it easier to replace it.

**Describe alternatives you've considered**
Another option would be to have it on the right side of the number inputs to make it easier to modify higher precision numbers (|0.6) vs (0.6|)

**Additional context**
The main spot I see this are the dial sliders like "Attribute Weights" or the "K" value in k-Anonymity.

![image](https://user-images.githubusercontent.com/19843782/186213558-26d31be5-8a3a-414a-94d1-36b0c1c6ddaf.png)

![image](https://user-images.githubusercontent.com/19843782/186213597-5a409abd-a54f-4425-82a4-484c676f8bdd.png)

In these cases, I suspect you are far more likely to replace what is there than add a number to the front of the value (especially with attribute weights because those would then be out of the appropriate range).

**Comment by prasser** [comment]
Thanks for suggesting this. Not sure whether selecting the whole value is a good idea, as this dialog is used in many places of ARX. But at least we should move the cursor to the right. We will do that.

**Comment by prasser** [comment]
Fix merged into master. Turned out that it was possible to implement this as you initially suggested: by selecting the whole value. Closing.
