### ISSUE TITLE
Check anonymity of a dataset

### ISSUE THREAD

**Issue by lacerated** [arx-deidentifier/arx#406]
I have data and would like to know if it satisfies entropy-l-diversity criteria. 
Noticed EntropyLDiversity class has isAnonymous() method, but have problems calling it. Figured how to anonymize data using that criterion, but is there is a way to find out if data is already anonymized without starting anonymization process?

Could some1 give me an example how to do that? (sorry i'm not good in java)

**Comment by prasser** [comment]
Yes, you can do this with ARX. You need to perform a simple anonymization process for this (without hierarchies, without record suppression, without local transformation etc.) and the result will basically reflect an assessment of the dataset. If you are not familiar with Java, you can also do this using the GUI version of ARX.

**Comment by lacerated** [comment]
> Yes, you can do this with ARX. You need to perform a simple anonymization process for this (without hierarchies, without record suppression, without local transformation etc.) and the result will basically reflect an assessment of the dataset. If you are not familiar with Java, you can also do this using the GUI version of ARX.

Was hoping to get true of false. Simple anonymization returns ARXResult object, next i need to compare anonimized dataset with initial data? If they r the same means it is already anonimized. Feels kinda complicated for simple task.
Just to clarify, there is no way to call isAnonymous() method on a dataset?

**Comment by prasser** [comment]
No need to compare anything. As I said, this will do an assessment and you can get true or false:

ARXResult result = ...;
boolean anonymous = result.getGlobalOptimum().getAnonymity() == Anonymity.ANONYMOUS;

**Comment by prasser** [comment]
Additional note: it is important to configure ARX correctly for this to work (no hierarchies, no aggregation functions, suppression limit of 0). Even more safe would be to call the following in the end:

boolean anonymous = result.getLattice().getBottom().getAnonymity() == Anonymity.ANONYMOUS;

**Comment by lacerated** [comment]
Thank you, think it works!
I like second option since it wont throw NullPointerException if data is not anonymized.

**Comment by prasser** [comment]
Great. Please close this issue, when your question has been resolved.
