### ISSUE TITLE
[BUG] The download links on the webpage are broken

### ISSUE THREAD

**Issue by ZachHaber** [arx-deidentifier/arx#409]
**Describe the bug**
On the [download page](https://arx.deidentifier.org/downloads/), All the links except the installer downloads are broken due to mixed content issues.

The redirected download links are on http instead of https. The win 64 jar file redirects to http://arx.deidentifier.org/wp-content/uploads/downloads/arx-3.9.0-win-64.jar, which triggers the mixed-content error.

**To Reproduce**
1. Go to https://arx.deidentifier.org/downloads/ on Chrome
2. Open the console and network tabs in the dev tools
3. Click on "Windows 64-Bit" in Runnable Jar Files
4. See that there's a mixed content error

**Expected behavior**
I expected the download buttons to download files, instead of silently failing (from a normal user perspective)

**Screenshots**
![image](https://user-images.githubusercontent.com/19843782/188980791-788976ab-5215-4bd5-a48d-4a582ab5738f.png)
![image](https://user-images.githubusercontent.com/19843782/188980810-1a9d0209-2f41-415f-8445-e25d3f352a5f.png)

**Comment by idhamari** [comment]
I can reproduce the issue in chrome. I noticed if I copy the link and paste in a new tab   e.g. 

https://arx.deidentifier.org/?ddownload=1917

It works and the file is downloaded!

**Comment by ZachHaber** [comment]
The issue is the mixed content in Chrome. By design, anything non-secure is blocked on a secure webpage.

**Comment by ZachHaber** [comment]
> I can reproduce the issue in chrome. I noticed if I copy the link and paste in a new tab   e.g. 
> 
> https://arx.deidentifier.org/?ddownload=1917
> 
> It works and the file is downloaded! 
> I don't have this error on Firefox so I think this is related to some ads/popup blocker! 
> 

Note: the main link you see when you hover over the download buttons is `https`, but that appears to redirect to an insecure `http` link to perform the actual download.

**Comment by prasser** [comment]
Thanks for reporting this. Fixed!
