### ISSUE TITLE
[BUG] ARX Help Center: 3.2. Specifying attribute properties outdated Attribute metadata section

### ISSUE THREAD

**Issue by jubeormk1** [arx-deidentifier/arx#413]
**Describe the bug**
In Version 3.9.0 ARX Help Center, section 3.2 Specifying attribute properties, subsection "Attribute metadata" refers the column "Response variable" instead of the current "Target variable". That happens both in the text and the illustrative image.

The incidence could be minimal but still it is inaccurate.

**To Reproduce**
1. Open ARX Anonymization Tool
2. Load a data set
3. Select the tab "Configure transformation"
4. In  the right panel select the "attribute metadata" tab
5. Click on the top right help icon (?) navigate to 3.2. ... Subsection "Attribute metadata"
6. Compare the fourth column from the program "Target variable" and the help content "Response variable"

**Expected behavior**
The help document should refer to "Target variable" instead of "Response variable"

**Screenshots**
![image](https://user-images.githubusercontent.com/48457722/190895457-617b1aa7-c7a5-4412-b19d-f98bfe6392c0.png)

**ARX GUI (please complete the following information):**
 - OS: Windows
 - Version 3.9.0

**Additional context**
No additional context required.

**Comment by idhamari** [comment]
The help should be updated soon!

**Comment by prasser** [comment]
This needs to go into the repo for the ARX help:

https://github.com/arx-deidentifier/arx-help

**Comment by idhamari** [comment]
The figure is corrected in thie [commit](https://github.com/arx-deidentifier/arx-help/pull/5/commits/0086f8fe35d7d0d53b536663baf73442d70dd69d)
