### ISSUE TITLE
[BUG] Arx doesn't start with SWTError: No more handles

### ISSUE THREAD

**Issue by muelli** [arx-deidentifier/arx#416]
**Describe the bug**
Cannot start ARX 3.9.0 gtk 64 on Linux

**To Reproduce**
1. Download https://github.com/arx-deidentifier/arx/releases/download/v3.9.0/arx-3.9.0-gtk-64.jar
2. java -jar arx-3.9.0-gtk-64.jar
3. See error

**Expected behavior**
I expected ARX to start or to at least give me some information how to futher debug the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/322807/195581189-47e3cd30-df73-49f3-970e-3fafd77aba8b.png)

**ARX GUI (please complete the following information):**
 - OS: Linux
 - Version 3.9.0

```
$ /opt/ARX-3.9.0/ARX-launcher.run 
OpenJDK 64-Bit Server VM warning: Option MaxRAMFraction was deprecated in version 10.0 and will likely be removed in a future release.
Gtk-Message: 13:03:02.037: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:03:02.037: Failed to load module "canberra-gtk-module"

(ARX Anonymization Tool:311): Gtk-WARNING **: 13:03:02.911: Negative content width -2 (allocation 11, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4749)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:151)
	at org.eclipse.swt.widgets.Display.getSystemCursor(Display.java:2862)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:62)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1083)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandAll(AbstractTreeViewer.java:1044)
	at org.deidentifier.arx.gui.view.impl.utility.ViewPropertiesInput.create(Unknown Source)
	at org.deidentifier.arx.gui.view.impl.utility.ViewPropertiesInput.<init>(Unknown Source)
	at org.deidentifier.arx.gui.view.impl.utility.LayoutUtilityStatistics.<init>(Unknown Source)
	at org.deidentifier.arx.gui.view.impl.utility.LayoutUtility.<init>(Unknown Source)
	at org.deidentifier.arx.gui.view.impl.MainWindow.<init>(Unknown Source)
	at org.deidentifier.arx.gui.Main.main(Unknown Source)
	at org.deidentifier.arx.gui.Main.main(Unknown Source)
[📦 org.deidentifier.arx ~]$ java --version
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment 18.9 (build 11.0.14+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14+8, mixed mode)
[📦 org.deidentifier.arx ~]$ 

```
**Additional context**

I've also used the installer just in case. But the error is the same.

**Comment by prasser** [comment]
Thanks for reporting this! Can you please provide the following info:

- Linux distribution and version
- Desktop environment and version
- Display server and version

**Comment by muelli** [comment]
I'm trying to run inside a bubblewrap sandbox through flatpak with X11.
I've pushed my progress here: https://github.com/muelli/flathub/tree/arx
You build the thing with something like `flatpak-builder --user --install --install-deps-from=flathub  --ccache --keep-build-dirs  --force-clean -v  --repo=/tmp/fb.repo fpbuilder org.deidentifier.arx.yaml` and then you can run, e.g. `flatpak run --user --command=bash org.deidentifier.arx`.

**Comment by prasser** [comment]
Phew. Seems to be a quite special environment. I believe that this bug is related to SWT (the GUI toolkit used by ARX) and not to ARX itself.

Have you tried running any other SWT-based software inside the same environment?

**Comment by muelli** [comment]
okay, I think I found the issue.
Running with another runtime, i.e. having more libraries, makes it run.
So some dependencies were missing, I guess.
I couldn't find a list, so I assumed that very little is required. And judging by the name, I guess that the release contains a copy of GTK, so I thought no other requirements need to be fulfilled. With the very big "GNOME" runtime it's running now.

While this particular issue can be closed, I think there are structural things that can be addressed, such as producing a more actionable error that actually helps the user.

I intend to suggest the app for distribution through flathub. Expect a ping with the question of whether you'd be willing to co-maintain the package. It's usually pretty low effort.

Thanks for being so responsive and, of course, for writing Free Software!
