### ISSUE TITLE
[BUG] Improper backward compatibility warning

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#426]
When creating a project using ARX version 3.9.1 and using the date hierarchy builder, the project cannot be opened with 3.9.0 and the error message “enum constant QUARTER_YEAR does not exist …” appears. A hint to upgrade to the new ARX version would be preferable.

![grafik](https://user-images.githubusercontent.com/9593020/201734266-ecff32aa-cc6e-4e11-a794-d34d51d0c81e.png)

Example project:
[arx_391_old_dates.zip](https://github.com/arx-deidentifier/arx/files/10005874/arx_391_old_dates.zip)

**Comment by prasser** [comment]
Can (obviously) only be fixed for future versions.
