### ISSUE TITLE
[FEATURE] How to Debug ARX using Eclipse?

### ISSUE THREAD

**Issue by unical1988** [arx-deidentifier/arx#450]
I would like to debug ARX code using Eclipse. How do I have to proceed to do so?

**Comment by prasser** [comment]
This should help (also read the comments):

https://github.com/iaBIH/arx/discussions/5

Works?

**Comment by idhamari** [comment]
> I would like to debug ARX code using Eclipse. How do I have to proceed to do so?

This is also a good tutorial about debugging in [eclipse](https://www.vogella.com/tutorials/EclipseDebugging/article.html).

**Comment by unical1988** [comment]
@prasser As suggested by the video here https://drive.google.com/file/d/11lFZk71YCDAIUUPjwAObhrOfC93V6w-D/view, it does not, I can't find the run as an application for the src/main/gui/Main.java file

**Comment by idhamari** [comment]
> it does not, I can't find the run as an application for the src/main/gui/Main.java file

Can you show what does not work? screenshots and/or videos of your steps would be helpful.

**Comment by unical1988** [comment]
@idhamari when I right click on the Main.java in the gui folder (org.de-indentifier.arx.gui) as the highlighted video shows, the list doesn't contain the option "run as an application" but just "run configuration". It must be a project setup problem, that I can't figure out anyway.

**Comment by idhamari** [comment]
@unical1988 can you make sure that your eclipse and java were installed correctly e.g. by trying to create any simple java project then compile it and run it in eclipse?

**Comment by unical1988** [comment]
@idhamari sure eclipse works ok.

**Comment by prasser** [comment]
Then it's likely that your project setup is not correct. Have you followed the steps described at the link exactly? Maybe delete the project and start again following the instructions?

**Comment by prasser** [comment]
You should not use Maven. Per default, ARX runs in Eclipse without Maven und the binaries are built using Ant (but you don't need to run Ant to be able to compile / debug ARX in Eclipse). As I said, something seems to be wrong with your project. It is, for example, important to not create a Maven project, but a Java project and to not add the Maven nature. Create a simple Java project following the steps in the tutorial linked above.

**Comment by unical1988** [comment]
I deleted and imported the project again as Java application, and it worked, I am able to open the GUI and debug the software. Now, if I have implementation inquiries (e.g., about the role of some method or a class in the code), how/where could I ask them?

**Comment by idhamari** [comment]
From [this](https://github.com/arx-deidentifier/arx/blob/master/contributing.md): When you have a general question about data anonymization or ARX, please do not create an issue but send us an email.

This probably will be useful to [have](https://github.com/arx-deidentifier/arx/issues/375)

**Comment by prasser** [comment]
Great. Will close this now.
