### ISSUE TITLE
Integration with Spark ? 

### ISSUE THREAD

**Issue by YannBrrd** [arx-deidentifier/arx#71]
Hi,

Very nice tool. Do you know anyone who ever used it as a Spark dependency? Would it make sense? 

Thanks.

Regards,
Yann

**Comment by prasser** [comment]
Hi Yann,

thanks for your interest in ARX.

We do know of companies that use ARX within cluster computing frameworks. Regarding Spark, we have had contact with people that wanted to develop a spark-integration, but we don't know what came out of the project. It can make sense to use ARX with Spark, but this depends on your exact goals and setup.

Best regards
Fabian

**Comment by oliveratutexas** [comment]
Do the people talking about integration mind sharing their contact information?
