### ISSUE TITLE
GUI Freeze While Scrolling Through Results

### ISSUE THREAD

**Issue by jgaupp** [arx-deidentifier/arx#78]
GUI freeze when scrolling through results.  Stack trace attached.  The only outstanding circumstance was probably quick switch from configuration to results, with an immediate attempt to scroll.  Otherwise, using a simple dataset and configuration for testing of the game theoretic model.

Per an email exchange with Dr. Prasser - "likely hit a rare race condition [in] the code which synchronizes the scroll position of both tables."

![stack](https://cloud.githubusercontent.com/assets/22179949/19779935/c7114f56-9c48-11e6-8b07-9208ae10a8a1.PNG)

**Comment by prasser** [comment]
Dear James,

thanks for reporting this bug. I have just commited a fix to the gta-branch, which consists of a significantly simplified re-implementation of the synchronization logic, which likely fixes the bug. 

Can you confirm that there are no differences from the functionality point-of-view? Just out of curiosity: which OS are you using?

Cheers
Fabian

**Comment by jgaupp** [comment]
I'll test it out.

I'm using Windows 10.

**Comment by prasser** [comment]
Thanks. Perfect! I'll close this issue for now. If you run into a new problem or encounter any changes in functionality, please open a new issue.
