### ISSUE TITLE
Height of column titles in tables too small - text truncated

### ISSUE THREAD

**Issue by kbabioch** [arx-deidentifier/arx#80]
Column titles in most tables are too small, which leads to text that is truncated (see screenshot):

![arx anonymization tool - example _020](https://cloud.githubusercontent.com/assets/1918279/19944360/e42faa04-a13b-11e6-96a8-e47f00b64344.png)

**Comment by prasser** [comment]
This seems to be a platform specific issue which I cannot replicate on Windows, OSX and Ubuntu/Unity. Both tables are implemented with Nebula NatTable from the Eclipse project (http://www.eclipse.org/nattable/).

If you are willing to fix this (which would be great!), you could try something like this:
https://www.eclipse.org/forums/index.php/t/405313/

Thanks!
Fabian

**Comment by kbabioch** [comment]
I've finally repoted the bug upstream, see [here][1]. They made some suggestions, but it didn't work out for me. Maybe someone more familiar with NatTable can have a look at it?

[1]: https://bugs.eclipse.org/bugs/show_bug.cgi?id=511784

**Comment by kbabioch** [comment]
My latest patch kind of fixes it (both DataTable as well as CompontentTable). There are minor issues with the overlayed image in the cell (the dot), which is displayed over the text, instead of next to it). Can you verify if this isn't destroying the user experience on other platforms (Windows, OSX)?

![screenshot](https://cloud.githubusercontent.com/assets/1918279/22696641/15c8c1d6-ed4f-11e6-99b7-f6d36b55e39c.png)

**Comment by prasser** [comment]
Thanks for your efforts! I am willing to try the change, but what do you mean by "my latest patch"? The result looks good to me, apart from the fact that the lower part of the window looks pretty ugly now (lots of empty space) Why is this?

**Comment by kbabioch** [comment]
Hm, this has actually nothing to do with the changed lines in this patchset. I've also updated SWT in the meantime (from the provided version 4.2.1 to 4.6.2), and with the newer version it looks different. When reverting SWT back to 4.2.1, it looks "fine":

![screenshot](https://cloud.githubusercontent.com/assets/1918279/22698128/fc7cb958-ed53-11e6-9ae2-454fffbe7fe5.png)

The only thing still broken is the background image of the row header and the "dots" in the cell. But that can be dealt with later on.

The "latest" patch is f0efe868022d0688e731e3cdccb3be9e85c5d864. It fixes both the DataTable as well as the ComponentTable. You should be fine by simply merging this PR.

**Comment by prasser** [comment]
Ok, perfect! I will pull this then. And always remember: never change a running system (or the underlying libraries) ;)

**Comment by prasser** [comment]
I pulled the PR. However, you changed the constructor call to "new TextPainter(false, false, true, true);" in method addNormalModeStyling(..) but didn't change it in addSelectedModeStyling(...). I have added that change to master.

Let's try to fix the image issue. What output do you get when you replace new BackgroundImagePainter(...); in addNormalModeStyling(...) with:

        final ICellPainter bgImagePainter = new BackgroundImagePainter(txtPainter,
                                                                       IMAGE_COL_BACK,
                                                                       GUIHelper.getColor(192, 192, 192)) {

                                                                        @Override
                                                                        public void
                                                                                paintCell(ILayerCell cell,
                                                                                          GC gc,
                                                                                          Rectangle rectangle,
                                                                                          IConfigRegistry configRegistry) {
                                                                            super.paintCell(cell, gc, rectangle, configRegistry);
                                                                            
                                                                            System.out.println(cell.getBounds() + "/" + rectangle);
                                                                        }
        };

**Comment by kbabioch** [comment]
That's right, forgot to change it in the second place :-).

This is the output:

    Rectangle {0, 0, 40, 20}/Rectangle {0, 0, 40, 20}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 100, 28}/Rectangle {360, 0, 98, 28}
    Rectangle {436, 0, 100, 28}/Rectangle {478, 0, 98, 28}
    Rectangle {536, 0, 100, 28}/Rectangle {578, 0, 98, 28}
    Rectangle {659, 0, 100, 28}/Rectangle {701, 0, 98, 28}
    Rectangle {759, 0, 100, 28}/Rectangle {801, 0, 98, 28}
    Rectangle {859, 0, 100, 28}/Rectangle {901, 0, 98, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 103, 28}/Rectangle {777, 0, 101, 28}
    Rectangle {838, 0, 145, 28}/Rectangle {880, 0, 143, 28}
    Rectangle {0, 0, 40, 20}/Rectangle {0, 0, 40, 20}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 100, 28}/Rectangle {360, 0, 98, 28}
    Rectangle {436, 0, 100, 28}/Rectangle {478, 0, 98, 28}
    Rectangle {536, 0, 100, 28}/Rectangle {578, 0, 98, 28}
    Rectangle {659, 0, 100, 28}/Rectangle {701, 0, 98, 28}
    Rectangle {759, 0, 100, 28}/Rectangle {801, 0, 98, 28}
    Rectangle {859, 0, 100, 28}/Rectangle {901, 0, 98, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 100, 28}/Rectangle {777, 0, 98, 28}
    Rectangle {835, 0, 145, 28}/Rectangle {877, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 100, 28}/Rectangle {777, 0, 98, 28}
    Rectangle {835, 0, 145, 28}/Rectangle {877, 0, 143, 28}
    Rectangle {0, 0, 40, 28}/Rectangle {0, 0, 40, 28}
    Rectangle {0, 0, 18, 28}/Rectangle {42, 0, 16, 28}
    Rectangle {118, 0, 100, 28}/Rectangle {160, 0, 98, 28}
    Rectangle {218, 0, 100, 28}/Rectangle {260, 0, 98, 28}
    Rectangle {318, 0, 184, 28}/Rectangle {360, 0, 182, 28}
    Rectangle {502, 0, 110, 28}/Rectangle {544, 0, 108, 28}
    Rectangle {612, 0, 123, 28}/Rectangle {654, 0, 121, 28}
    Rectangle {735, 0, 100, 28}/Rectangle {777, 0, 98, 28}
    Rectangle {835, 0, 145, 28}/Rectangle {877, 0, 143, 28}

According to the upstream comment [1], we need to scale the image for ourselves :-(.

[1]: https://bugs.eclipse.org/bugs/show_bug.cgi?id=511784

**Comment by prasser** [comment]
Indeed. Can you please check whether the current master solves the issue for you?

**Comment by kbabioch** [comment]
Yup, works fine now:

![screenshot](https://cloud.githubusercontent.com/assets/1918279/22706698/829af448-ed70-11e6-840f-88a53c6b9b50.png)
